/**
 * This file is auto-generated by generateGrpcClient.js.
 * It exports a grpcClient object with functions for each gRPC method.
 *
 * Example usage:
 *   import { grpcClient } from './grpcClient.js';
 *   (async () => {
 *     const result = await grpcClient["cosmwasm.wasm.v1.Query"].Code({ code_id: 123 });
 *     console.log(result);
 *   })();
 */

import { exec } from 'child_process';
import { promisify } from 'util';
const execAsync = promisify(exec);
const GRPC_SERVER = "grpc.mantrachain.io:443";

async function callGrpc(service, method, payload) {
  const fqMethod = `${service}/${method}`;
  const jsonPayload = JSON.stringify(payload);
  // Using grpcurl to call the method with JSON input
  const cmd = `grpcurl -d '${jsonPayload}' ${GRPC_SERVER} ${fqMethod}`;
  try {
    const { stdout } = await execAsync(cmd);
    return JSON.parse(stdout);
  } catch (error) {
    throw new Error(`Failed to call ${fqMethod}: ${error.message}`);
  }
}

export const grpcClient = {
  "cosmwasm.wasm.v1.Query": {
    AllContractState: async (payload) => await callGrpc("cosmwasm.wasm.v1.Query", "AllContractState", payload),
    BuildAddress: async (payload) => await callGrpc("cosmwasm.wasm.v1.Query", "BuildAddress", payload),
    Code: async (payload) => await callGrpc("cosmwasm.wasm.v1.Query", "Code", payload),
    CodeInfo: async (payload) => await callGrpc("cosmwasm.wasm.v1.Query", "CodeInfo", payload),
    Codes: async (payload) => await callGrpc("cosmwasm.wasm.v1.Query", "Codes", payload),
    ContractHistory: async (payload) => await callGrpc("cosmwasm.wasm.v1.Query", "ContractHistory", payload),
    ContractInfo: async (payload) => await callGrpc("cosmwasm.wasm.v1.Query", "ContractInfo", payload),
    ContractsByCode: async (payload) => await callGrpc("cosmwasm.wasm.v1.Query", "ContractsByCode", payload),
    ContractsByCreator: async (payload) => await callGrpc("cosmwasm.wasm.v1.Query", "ContractsByCreator", payload),
    Params: async (payload) => await callGrpc("cosmwasm.wasm.v1.Query", "Params", payload),
    PinnedCodes: async (payload) => await callGrpc("cosmwasm.wasm.v1.Query", "PinnedCodes", payload),
    RawContractState: async (payload) => await callGrpc("cosmwasm.wasm.v1.Query", "RawContractState", payload),
    SmartContractState: async (payload) => await callGrpc("cosmwasm.wasm.v1.Query", "SmartContractState", payload),
    WasmLimitsConfig: async (payload) => await callGrpc("cosmwasm.wasm.v1.Query", "WasmLimitsConfig", payload),
  },
};
