#!/usr/bin/env node
/**
 * generateGrpcClient.js
 *
 * This script uses grpcurl to discover cosmwasm-related gRPC services and their methods,
 * then generates an ES module (grpcClient.js) that exports a grpcClient object.
 *
 * Each method is exposed as an async function that executes a grpcurl call with a JSON payload.
 *
 * Usage:
 *   node generateGrpcClient.js [grpc_server_address] [output_file]
 *
 * Defaults:
 *   grpc_server_address: grpc.mantrachain.io:443
 *   output_file: grpcClient.js (in the current working directory)
 */

import { exec } from 'child_process';
import { promisify } from 'util';
import fs from 'fs/promises';
import path from 'path';

const execAsync = promisify(exec);
const GRPC_SERVER = process.argv[2] || 'grpc.mantrachain.io:443';
const OUTPUT_FILE = process.argv[3] || 'grpcClient.js';

/**
 * List all services from the gRPC server and filter those that contain "cosmwasm".
 */
async function listServices() {
  const { stdout } = await execAsync(`grpcurl ${GRPC_SERVER} list`);
  const services = stdout
    .split('\n')
    .map(line => line.trim())
    .filter(line => line.includes('cosmwasm'));
  return services;
}

/**
 * Parse rpc methods from a service description.
 * Looks for lines like:
 *   rpc MethodName ( .package.RequestType ) returns ( .package.ResponseType ) { ... }
 */
function parseRpcMethods(serviceDesc) {
  const methodRegex = /rpc\s+(\w+)\s*\(\s*([^)]+?)\s*\)\s+returns\s*\(\s*([^)]+?)\s*\)/g;
  let match;
  const methods = [];
  while ((match = methodRegex.exec(serviceDesc)) !== null) {
    const methodName = match[1].trim();
    // We only need the method name for client function generation
    methods.push(methodName);
  }
  return methods;
}

/**
 * Retrieve the full service description using grpcurl.
 */
async function describeService(service) {
  const { stdout } = await execAsync(`grpcurl ${GRPC_SERVER} describe ${service}`);
  return stdout;
}

/**
 * Build the gRPC client definition mapping each service to its methods.
 */
async function buildGrpcClientDefinition() {
  const clientDef = {};
  const services = await listServices();
  for (const service of services) {
    console.log(`Processing service: ${service}`);
    const serviceDesc = await describeService(service);
    const methods = parseRpcMethods(serviceDesc);
    if (methods.length > 0) {
      clientDef[service] = methods;
    }
  }
  return clientDef;
}

/**
 * Generate the ES module file that exports the grpcClient.
 * This version uses string concatenation (with single quotes) to avoid issues with nested backticks.
 */
async function generateClientFile() {
  const grpcClientDef = await buildGrpcClientDefinition();

  // Build the output file content using concatenated strings.
  let output = '/**\n' +
' * This file is auto-generated by generateGrpcClient.js.\n' +
' * It exports a grpcClient object with functions for each gRPC method.\n' +
' *\n' +
' * Example usage:\n' +
' *   import { grpcClient } from \'./grpcClient.js\';\n' +
' *   (async () => {\n' +
' *     const result = await grpcClient["cosmwasm.wasm.v1.Query"].Code({ code_id: 123 });\n' +
' *     console.log(result);\n' +
' *   })();\n' +
' */\n\n' +
'import { exec } from \'child_process\';\n' +
'import { promisify } from \'util\';\n' +
'const execAsync = promisify(exec);\n' +
'const GRPC_SERVER = "' + GRPC_SERVER + '";\n\n' +
'async function callGrpc(service, method, payload) {\n' +
'  const fqMethod = `${service}/${method}`;\n' +
'  const jsonPayload = JSON.stringify(payload);\n' +
'  // Using grpcurl to call the method with JSON input\n' +
'  const cmd = `grpcurl -d \'${jsonPayload}\' ${GRPC_SERVER} ${fqMethod}`;\n' +
'  try {\n' +
'    const { stdout } = await execAsync(cmd);\n' +
'    return JSON.parse(stdout);\n' +
'  } catch (error) {\n' +
'    throw new Error(`Failed to call ${fqMethod}: ${error.message}`);\n' +
'  }\n' +
'}\n\n' +
'export const grpcClient = {\n';

  // Generate function definitions for each service and method.
  for (const [service, methods] of Object.entries(grpcClientDef)) {
    output += '  "' + service + '": {\n';
    for (const method of methods) {
      output += '    ' + method + ': async (payload) => await callGrpc("' + service + '", "' + method + '", payload),\n';
    }
    output += '  },\n';
  }
  
  output += '};\n';

  const outputPath = path.resolve(process.cwd(), OUTPUT_FILE);
  await fs.writeFile(outputPath, output, 'utf8');
  console.log('gRPC client library generated at: ' + outputPath);
}

generateClientFile().catch(err => {
  console.error("Error generating gRPC client library:", err);
});
